### PR TITLE
I2o restarts

### PR DESCRIPTION
**Pull request by russfiedler**
This change defines all restart variables in `i2o.nc` in one go and then writing rather than defining and writing each one individually. This potentially avoids needless copying when redefining variables.

### CODE REVIEW

**Comment by russfiedler** [comment]
A similar issue affects MOM. Since it's a much simpler decomposition I'm sure it could be solved using the standard io_layout. Still the redefining of variable is an issue.

**Comment by aidanheerdegen** [comment]
Not having much joy with this @russfiedler, want me to review?

**Comment by russfiedler** [comment]
Thanks. That would be great..

**Comment by aidanheerdegen** [comment]
This is the original zombie PR. I started tested it a couple of weeks ago, and of course ... anyway. I ran the vanilla `1deg_jra55_ryf` config with `cdb90109bbd9e58509b7a63b2f6e087bdf6a2411` and compiled this PR and ran same config. Results were identical.

**Pull request merged**
